development:
    adapter: sqlite3
    database: db/development.sqlite3
    pool: 5
    timeout: 5000
production:
    adapter: mysql
    encoding: utf8
    username: balder
    password: changeme
    database: balder_production
    socket: /var/run/mysqld/mysqld.sock
test: &TEST
    adapter: postgresql
    database: gallery_test
    username: balder
    password: changeme

cucumber:
  <<: *TEST